config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "events#index"
  resources :users, only: [:show, :edit, :update]
  resources :events do
    resources :comments, only: :create
    resources :bookings, only: [:index, :create]
  end
  resources :messages, only: [:create]
  resources :rooms, only: [:create, :index, :show]

end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  mount_uploader :avatar, AvatarUploader
  has_one_attached :avatar

  validates :password, presence: true, on: :create
  validates :name, presence: true
  validates :profile, presence: true
  validates :occupation, presence: true
  validates :language, presence: true
  validates :avatar, presence: true
  validates :avatar_cache, presence: true

  # VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
  # validates :password, format: { with: VALID_PASSWORD_REGEX }

  has_many :events
  has_many :comments
  has_many :bookings
  has_many :entries, dependent: :destroy
  has_many :messages, dependent: :destroy
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  protected

  # アカウント登録後のリダイレクト先
  def after_sign_up_path_for(_resource)
    root_path
  end

  # パスワードなしで更新できるメソッド
  def update_resource(resource, params)
    resource.update_without_password(params)
  end

  # アカウント編集後のリダイレクト先
  def after_update_path_for(resource)
    user_path(resource)
  end

  private

  def sign_up_params
    params.require(:user).permit(:email, :password, :password_confirmation, :name, :occupation, :language, :profile, :avatar,
                                 :avatar_cache)
  end

  def account_update_params
    params.require(:user).permit(:name, :occupation, :language, :profile, :avatar, :avatar_cache)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @name = @user.name
    @events = @user.events
    @current_entry = Entry.where(user_id: current_user.id)
    @another_entry = Entry.where(user_id: @user.id)
    return if @user.id == current_user.id

    @current_entry.each do |current|
      @another_entry.each do |another|
        if current.room_id == another.room_id
          @is_room = true
          @room_id = current.room_id
        end
      end
    end
    return if @is_room

    @room = Room.new
    @entry = Entry.new
  end

  def edit
    # 編集ページの処理を実装
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      redirect_to edit_user_path(@user)
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :occupation, :language, :profile, :avatar)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">ユーザー情報編集</h2>

     <%= form_with(model: @user, local: true) do |f| %>
        <div class="field">
          <%= f.label :avatar, "プロフィール画像" %><br />
          <%= image_tag @user.avatar.url, class: 'avatar', id: 'preview'%><br />
          <%= f.file_field :avatar %>
        </div>


        <div class="field">
          <%= f.label :name, "ユーザー名 (ニックネーム)" %><br />
          <%= f.text_field :name, id:"user_name" %>
        </div>

        <div class="field">
          <%= f.label :occupation, "職業" %><br />
          <%= f.text_area :occupation, class: :form__text, id:"user_occupation" %>
        </div>

        <div class="field">
          <%= f.label :language, "使用言語" %><br />
          <%= f.text_area :language, class: :form__text, id:"user_position" %>
        </div>

         <div class="field">
          <%= f.label :profile, "プロフィール" %><br />
          <%= f.text_area :profile, class: :form__text, id:"user_profile" %>
        </div>


        <div class="actions">
          <%= f.submit "更新する", class: :form__btn  %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="main">
  <div class="inner">
    <div class="user__wrapper">
      <h2 class="page-heading">
        <%= "#{@user.name}さんの情報"%>
      </h2>
      
      <% if user_signed_in? && current_user.id == @user.id  %>
        <div class="user__manage">
          <%= link_to "編集する", edit_user_path(@user.id), class: :user__btn %>
        </div>
      <% end %>

      <%# 個別メッセージ機能 %>
        <% unless @user.id == current_user.id %>
          <% if @is_room == true %>
            <%= link_to '個別メッセージへ', room_path(@room_id), class: :pv__message %><br>
          <% else %>
            <%= form_for @room do |f| %>
              <%= fields_for @entry do |e| %>
                <%= e.hidden_field :user_id, value: @user.id %>
              <% end %>
              <%= f.button type: :submit, class: 'pv__message' do %>
                個別相談ルームへ！
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <%# 個別メッセージ機能はここまで %>

      <%# プロフィール画像 class名は仮%>
      <%= image_tag @user.avatar.url, class: :avatar %>
      <%# プロフィール画像はここまで class名は仮%>
     

      <table class="table">
        <tbody>
          <tr>
            <th class="table__col1">名前</th>
            <td class="table__col2"><%= @user.name %></td>
          </tr>
          <tr>
            <th class="table__col1">職業</th>
            <td class="table__col2"><%= @user.occupation %></td>
          </tr>
          <tr>
            <th class="table__col1">使用言語</th>
            <td class="table__col2"><%= @user.language %></td>
          </tr>
          <tr>
            <th class="table__col1">プロフィール</th>
            <td class="table__col2"><%= @user.profile %></td>
          </tr>
        </tbody>
      </table>
      <h2 class="page-heading">
        <%= @user.name + "さんのイベント一覧"%>
      </h2>
      <div class="user__card">
        <%= render partial: 'events/event', collection: @events.order(created_at: :desc) %>
      </div>
    </div>
  </div>
</div>