config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "events#index"
  resources :users, only: [:show, :edit, :update]
  resources :events do
    resources :comments, only: :create
    resources :bookings, only: [:index, :create]
  end
  resources :messages, only: [:create]
  resources :rooms, only: [:create, :index, :show]

end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many_attached :images
  has_one :booking

  validates :title, presence: true
  validates :catch_copy, presence: true
  validates :concept, presence: true
  validates :images, presence: true
  validates :price, presence: true
  validates :address, presence: true
  validates :price, numericality: { only_integer: true, message: 'Half-width number' }
  validates :price,
            numericality: { greater_than_or_equal_to: 300, less_than_or_equal_to: 9_999_999, message: 'Out of setting range' }
  validates :images, length: { minimum: 1, maximum: 10, message: 'は1枚以上10枚以下にしてください' }

  geocoded_by :address
  after_validation :geocode, if: :address_changed?
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :destroy, :update]
  before_action :set_event, only: [:edit, :show, :update, :destroy, :move_to_index]
  before_action :move_to_index, except: [:index, :show, :new, :create]

  def index
    @events = Event.includes(:user).order('created_at DESC')
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to @event
    else
      render :new
    end
  end

  def show
    @comment = Comment.new
    @comments = @event.comments.includes(:user)
    @event = Event.find(params[:id])

    # 住所の整形
    address_parts = @event.address.split(' ')
    @street = address_parts[0..-2].join(' ')

    @locations = [
      { 'lat' => @event.latitude, 'lng' => @event.longitude }
    ]
  end

  def edit
  end

  def update
    if @event.update(event_params)
      redirect_to event_path
    else
      render :edit
    end
  end

  def destroy
    @event.bookings.destroy_all
    @event.destroy
    redirect_to root_path
  end

  private

  def event_params
    params.require(:event).permit(:title, :catch_copy, :concept, :price, :address, :latitude, :longitude,
                                  { images: [] }).merge(user_id: current_user.id)
  end

  def set_event
    @event = Event.find(params[:id])
  end

  def move_to_index
    return if user_signed_in? && current_user.id == @event.user_id

    redirect_to action: :index
  end
end

app/views/events/_event.html.erb
<div class="card">
  <%= link_to image_tag(event.images[0], class: :card__img ), event_path(event.id) if event.images.attached? %>
  <div class="card__body">
    <%= link_to event.title, event_path(event.id), class: :card__title %>
    <p class="card__summary">
      <%= event.catch_copy %>
    </p>
    <p class="card__price">
      <%= event.price %>円 / 泊
    </p>
   <%= link_to "by " +  event.user.name, user_path(event.user.id), class: :card__user %>
  </div>
</div>

app/views/events/_form.html.erb
<%= form_with model: event, id: 'new_event', local: true do |f|%>
<%= render 'shared/error_messages', model: f.object %>
  <div class="field">
    <%= f.label :title, "イベントの名称" %><br />
    <%= f.text_field :title, id:"event_title" %>
  </div>

  <div class="field">
    <%= f.label :catch_copy, "体験できること" %><br />
    <%= f.text_area :catch_copy, class: :form__text, id:"event_catch_copy" %>
  </div>

  <div class="field">
    <%= f.label :concept, "料金に含まれるもの" %><br />
    <%= f.text_area :concept, class: :form__text, id:"event_concept" %>
  </div>

  <div class="field">
    <%= f.label :image, "イベントと宿のイメージ画像（最大10枚）" %><br />
    <div id="previews"></div>
    <%= f.file_field :images, name: 'event[images][]', data: {index: 0} %>
  </div>

  <div class="field">
    <%= f.label :price, "イベントの料金（宿泊費込み）" %><br />
    <%= f.text_field :price, id:"event_fee" %>円
  </div>

  <div class="field">
    <%= f.label :address, "イベントの場所" %><br />
    <%= f.text_field :address, id:"event_place" %>
  </div>

  <div class="actions">
    <%= f.submit "公開する", class: :form__btn  %>
  </div>
<% end %>

app/views/events/edit.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">プロトタイプ編集</h2>
      <%= render partial: "form", locals: { event: @event } %>
    </div>
  </div>
</div>

app/views/events/index.html.erb
<main class="main">
  <div class="inner">
    <% if user_signed_in? %>
      <div class="greeting">
        こんにちは、
        <%= link_to "#{current_user.name}さん", "/users/#{current_user.id}", class: :greeting__link%>
      </div> 
    <% end %>
    <div class="card__wrapper">
      <%= render partial: 'event', collection: @events %>
    </div>
  </div>
</main>

app/views/events/new.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">新規イベント投稿</h2>
        <%= render partial: "form", locals: { event: @event } %>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<main class="main">
  <div class="inner">
    <div class="event__wrapper">
      <p class="event__hedding">
        <%= @event.title %>
        <%= @event.price %>円 / 泊
      </p>
    
      
      <%= link_to "by " + @event.user.name, user_path(@event.user), class: :event__user %>
      <% if user_signed_in? %>
        <div class="event__manage">
        <% if current_user.id == @event.user.id %>
          <%= link_to "編集する", edit_event_path(@event.id), class: :event__btn %>
          <%= link_to "削除する", event_path(@event.id), method: :delete, class: :event__btn %>
        <% else %>
          <%= link_to "予約画面に進む", event_bookings_path(@event),class: :event__orange__btn %>
        <% end %>
        </div>
      <% end %>
      <div class="event__image">
        <% if @event.images.attached? %>
          <% @event.images.each do |image| %>
             <%= image_tag image.variant(resize: '500x500').processed %>
          <% end %>
        <% end %>
      </div>
      <div class="event__body">
        <div class="event__detail">
          <p class="detail__title">体験できること</p>
          <p class="detail__message">
            <%= @event.catch_copy %>
          </p>
        </div>
        <div class="event__detail">
          <p class="detail__title">料金に含まれるもの</p>
          <p class="detail__message">
            <%= @event.concept %>
          </p>
        </div>
       
        <%# google maps api 埋め込み %>
        <h3>イベント＆宿泊場所（＊大体の位置です。住所詳細は予約確定時にお伝えします。）</h3>
        <div class="address">
          <p><%= @street %></p>
        </div>

        <div class="map">
          <div id="map"></div>
        </div>

        <script>
          function initMap() {
            const map = new google.maps.Map(document.getElementById('map'), {
              center: { lat: <%= @event.latitude %>, lng: <%= @event.longitude %> },
              zoom: 15
            });

            const marker = new google.maps.Marker({
              position: { lat: <%= @event.latitude %>, lng: <%= @event.longitude %> },
              map: map,
              title: '<%= @event.title %>'
            });
          }
        </script>
        <script src="https://maps.googleapis.com/maps/api/js?key=<%=  ENV['GOOGLE_MAP_API_KEY'] %>&callback=initMap" defer></script>
        <%# google maps api埋め込み  %>

      </div>
      <div class="event__comments">
        <% if user_signed_in? %>
          <%= form_with model:  [@event, @comment],local: true do |f|%>
            <div class="field">
              <%= f.label :content, "コメント" %><br />
              <%= f.text_field :content, id:"comment_content" %>
            </div>
            <div class="actions">
              <%= f.submit "送信する", class: :form__btn  %>
            </div>
          <% end %>
        <% end %>
        <ul class="comments_lists">
          <% @comments.each do |comment| %>
            <li class="comments_list">
              <%= comment.content%>
              <%= link_to comment.user.name, user_path(comment.user.id) , class: :comment_user %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</main>