config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "events#index"
  resources :users, only: [:show, :edit, :update]
  resources :events do
    resources :comments, only: :create
    resources :bookings, only: [:index, :create]
  end
  resources :messages, only: [:create]
  resources :rooms, only: [:create, :index, :show]

end

app/models/room.rb
class Room < ApplicationRecord
  has_many :entries, dependent: :destroy
  has_many :messages, dependent: :destroy
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!
  def create
    room = Room.create
    current_entry = Entry.create(user_id: current_user.id, room_id: room.id)
    another_entry = Entry.create(user_id: params[:entry][:user_id], room_id: room.id)
    redirect_to room_path(room)
  end

  def index
    # ログインユーザー所属ルームID取得
    current_entries = current_user.entries
    my_room_id = []
    current_entries.each do |entry|
      my_room_id << entry.room.id
    end
    # 自分のroom_idでuser_idが自分じゃないのを取得
    @another_entries = Entry.where(room_id: my_room_id).where.not(user_id: current_user.id).order(created_at: :desc)
  end

  def show
    @room = Room.find(params[:id])
    @messages = @room.messages.all
    @message = Message.new
    @entries = @room.entries
    @another_entry = @entries.where.not(user_id: current_user.id).first
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/index.html.erb
<div class="m-wrappper">
  <div class="m-title">
    <%= "#{current_user.name}さんのメッセージ一覧" %>
  </div>

  <% @another_entries.each do |entry| %>
    <%= link_to room_path(entry.room) do %>
      <div class="cards">
        <div class="card-body">
        
            <div class="d-flex">
              <div class="chat-avatar">
                <object>
                  <%= link_to user_path(entry.user.id) do %>
                    <%= image_tag entry.user.avatar.url %>
                  <% end %>
                </object>
              </div>
              <div class="chat-user-name">
                <%= entry.user.name %>
              </div>
            </div>
            <div class="chat-text">
              <% message = Message.find_by(id: entry.room.message_ids.last)&.body %>
              <% truncated_message = truncate(message, length: 10, omission: '...') %>
              <%= truncated_message %>
            </div>
          </div>
      </div>
    <% end %>
  <% end %>

</div>

app/views/rooms/show.html.erb
<div class="message__area">
  <div class="line__container">
    <!-- タイトル -->
    <div class="line__title">
      <%= "#{@another_entry.user.name}さんとのメッセージ" %>
    </div>
    
    <!-- 会話エリア -->
    <div class="line__contents scroll">
      <% @messages.each do |m| %>
        <!-- 自分の吹き出し -->
        <% if m.user_id == current_user.id %>
          <div class="line__right">
            <div class="text">
              <%= format_newline(m.body) %>
            </div>
          </div>
        <!-- 相手の吹き出し -->
        <% else %>
          <div class="line__left">
            <figure>
              <%= image_tag m.user.avatar.url %>
            </figure>
            <div class="line__left-text">
              <div class="name"><%= m.user.name %></div>
              <div class="text"><%= format_newline(m.body) %></div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>

  </div>

  <div class="chat-form-box">
    <%= form_for @message do |f| %>
      <div class="chat-form-group">
        <%= f.text_area :body, placeholder:"メッセージを入力してください" %>
        <%= f.hidden_field :room_id, value: @room.id %>
        <%= f.submit "送信する" %>
      </div>
    <% end %>
  </div>
</div>