config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "events#index"
  resources :users, only: [:show, :edit, :update]
  resources :events do
    resources :comments, only: :create
    resources :bookings, only: [:index, :create]
  end
  resources :messages, only: [:create]
  resources :rooms, only: [:create, :index, :show]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :event
  has_one :guest, dependent: :destroy
end

app/models/booking_guest.rb
class BookingGuest
  include ActiveModel::Model
  attr_accessor :user_id, :event_id, :last_name, :first_name, :phone_number, :email, :checkin, :checkout, :message, :adult,
                :child, :infant, :token

  with_options presence: true do
    # bookingモデルのバリデーション
    validates :user_id
    validates :event_id
    # guestモデルのバリデーション
    validates :last_name
    validates :first_name
    validates :phone_number, format: { with: /\A\d{10,11}\z/, allow_blank: true, message: 'is invalid' }
    validates :email
    validates :checkin
    validates :checkout
    validates :adult, numericality: { only_integer: true, message: 'Half-width number' }
    validates :child, numericality: { only_integer: true, message: 'Half-width number' }
    validates :token
  end

  def save
    # 予約情報を保存し、変数bookingに代入する
    booking = Booking.create(user_id: user_id, event_id: event_id)
    # ゲストの情報を保存する
    Guest.create(last_name: last_name, first_name: first_name, phone_number: phone_number, email: email, checkin: checkin,
                 checkout: checkout, message: message, adult: adult, child: child, infant: infant, booking_id: booking.id)
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :event

  validates :content, presence: true
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many_attached :images
  has_one :booking

  validates :title, presence: true
  validates :catch_copy, presence: true
  validates :concept, presence: true
  validates :images, presence: true
  validates :price, presence: true
  validates :address, presence: true
  validates :price, numericality: { only_integer: true, message: 'Half-width number' }
  validates :price,
            numericality: { greater_than_or_equal_to: 300, less_than_or_equal_to: 9_999_999, message: 'Out of setting range' }
  validates :images, length: { minimum: 1, maximum: 10, message: 'は1枚以上10枚以下にしてください' }

  geocoded_by :address
  after_validation :geocode, if: :address_changed?
end

app/models/guest.rb
class Guest < ApplicationRecord
  belongs_to :booking
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/prototype.rb
class Prototype < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_one_attached :image

  validates :title, presence: true
  validates :catch_copy, presence: true
  validates :concept, presence: true
  validates :image, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :entries, dependent: :destroy
  has_many :messages, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  mount_uploader :avatar, AvatarUploader
  has_one_attached :avatar

  validates :password, presence: true, on: :create
  validates :name, presence: true
  validates :profile, presence: true
  validates :occupation, presence: true
  validates :language, presence: true
  validates :avatar, presence: true
  validates :avatar_cache, presence: true

  # VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
  # validates :password, format: { with: VALID_PASSWORD_REGEX }

  has_many :events
  has_many :comments
  has_many :bookings
  has_many :entries, dependent: :destroy
  has_many :messages, dependent: :destroy
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!
  def create
    room = Room.create
    current_entry = Entry.create(user_id: current_user.id, room_id: room.id)
    another_entry = Entry.create(user_id: params[:entry][:user_id], room_id: room.id)
    redirect_to room_path(room)
  end

  def index
    # ログインユーザー所属ルームID取得
    current_entries = current_user.entries
    my_room_id = []
    current_entries.each do |entry|
      my_room_id << entry.room.id
    end
    # 自分のroom_idでuser_idが自分じゃないのを取得
    @another_entries = Entry.where(room_id: my_room_id).where.not(user_id: current_user.id).order(created_at: :desc)
  end

  def show
    @room = Room.find(params[:id])
    @messages = @room.messages.all
    @message = Message.new
    @entries = @room.entries
    @another_entry = @entries.where.not(user_id: current_user.id).first
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @name = @user.name
    @events = @user.events
    @current_entry = Entry.where(user_id: current_user.id)
    @another_entry = Entry.where(user_id: @user.id)
    return if @user.id == current_user.id

    @current_entry.each do |current|
      @another_entry.each do |another|
        if current.room_id == another.room_id
          @is_room = true
          @room_id = current.room_id
        end
      end
    end
    return if @is_room

    @room = Room.new
    @entry = Entry.new
  end

  def edit
    # 編集ページの処理を実装
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      redirect_to edit_user_path(@user)
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :occupation, :language, :profile, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def format_newline(text)
    text.gsub("\n", '<br>').html_safe
  end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/prototypes_helper.rb
module PrototypesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>inaka-ikotto</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script type="text/javascript" src="https://js.pay.jp/v2/pay.js"></script>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
    <%= favicon_link_tag('favicon.png') %>
  </head>

  <body>
    <header class="header">
      <div class="inner">
        <div class="nav">
          <div class="nav__left">
            <%= link_to image_tag("logo.png", class: :logo), root_path %>
          </div>
          <% if user_signed_in? %>
            <div class="nav__right"> 
              <%= link_to "New Event", new_event_path, class: :nav__btn %>
              <%= link_to "メッセージ", rooms_path, class: :nav__message %>
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: :nav__logout %>
            </div> 
          <% else %>
            <div class="nav__right">
              <%= link_to "ログイン", new_user_session_path, class: :nav__btn %>
              <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
            </div>
          <% end %>
        </div>
      </div>
    </header>
    <%= yield %>
    <footer class="footer">
      <p class="copyright">Copyright © inaka-ikotto All rights reserved.</p>
    </footer>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="error-alert">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li class="error-message">
          <%= message %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>